"use strict";
let lines = "________________________________________________________";
console.log(`${lines}`);
let num = 2;
console.log(`Addition ${num + 6}`);
console.log(`${lines}`);
console.log(`Subtraction ${10 - num}`);
console.log(`${lines}`);
console.log(`Multiplication ${num * 4}`);
console.log(`${lines}`);
console.log(`Division ${16 / num}`);
console.log(`${lines}`);
